// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomField: typeof import('./src/components/common/Forms/CustomField.vue')['default']
    FormItemPicker: typeof import('./src/components/Forms/FormItemPicker.vue')['default']
    FormItemView: typeof import('./src/components/Forms/FormItemView.vue')['default']
    FormView: typeof import('./src/components/common/Forms/FormView.vue')['default']
    OrganismName: typeof import('./src/components/page/page_name/OrganismName.vue')['default']
    ProductCard: typeof import('./src/components/common/ProductCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
